on:
  push:
    paths-ignore:
      - 'changelog/**'

  pull_request:
  workflow_call:

jobs:
  run-pre-commit:
    name: Run pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '^3.10'

      - name: Install pre-commit
        run: |
          pip install pre-commit

      - name: Run linters
        run: |
          export PATH=$HOME/.cache/bin:$PATH
          pre-commit run --all-files

  run-linters:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.18'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49.0
